//! OS trust store installation for the PortZero local CA.
//!
//! Installs the self-signed CA generated by [`super::ca`] into the platform
//! trust stores so browsers and `curl` accept `*.portzero.local` HTTPS certs
//! without warnings.
//!
//! ## Linux — two independent stores
//!
//! 1. **System CA bundle** — adds the cert to the distro CA store so OpenSSL
//!    and system tools trust it immediately.  Requires the root privileges the
//!    daemon already holds for TUN device creation.
//!    - Debian/Ubuntu: copy to `/usr/local/share/ca-certificates/` + `update-ca-certificates`
//!    - RHEL/Fedora:   copy to `/etc/pki/ca-trust/source/anchors/` + `update-ca-trust extract`
//!
//! 2. **NSS databases** (Chrome, Chromium, Firefox) — browsers maintain their
//!    own certificate stores independent of the system CA bundle.  Added via
//!    `certutil` (from the `libnss3-tools` / `nss-tools` package).  This is
//!    best-effort: if `certutil` is absent a clear, actionable warning is logged.
//!
//! ## macOS — two independent stores
//!
//! 1. **System Keychain** (`/Library/Keychains/System.keychain`) — covers
//!    Safari, Chrome, curl, and all other tools that delegate to Secure
//!    Transport.  Uses `security add-trusted-cert -d -r trustRoot`.  Requires
//!    the root privileges the daemon already holds for TUN device creation.
//!
//! 2. **Firefox NSS databases** — Firefox maintains its own NSS cert store
//!    independent of the system keychain.  Added via `certutil` from the `nss`
//!    Homebrew formula (`brew install nss`).  Best-effort with a warning if
//!    absent.
//!
//! Uninstall reverses both steps.  Both operations are idempotent.
//!
//! # Design for testability
//!
//! Pure helpers (`system_cert_dest`, `find_nss_dbs`, `certutil_add_args`, …)
//! are `pub(crate)` for unit testing without touching the real system.  Impure
//! shims (`install_impl`, `uninstall_impl`) are kept thin.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

const CERT_NICKNAME: &str = "PortZero Local CA";
const SYSTEM_CERT_NAME: &str = "portzero-local-ca.crt";

/// Install the PortZero local CA into OS trust stores.
///
/// `ca_cert_path` is the on-disk path of the PEM file (as returned by
/// [`super::ca::LocalCa::ca_cert_path`]).  The file must already exist.
pub fn install(ca_cert_path: &Path) -> Result<()> {
    install_impl(ca_cert_path)
}

/// Remove the PortZero local CA from OS trust stores.
pub fn uninstall() -> Result<()> {
    uninstall_impl()
}

// ---------------------------------------------------------------------------
// Linux
// ---------------------------------------------------------------------------

/// Which distro-level CA update tool is present.
#[cfg(target_os = "linux")]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum LinuxCaTool {
    /// Debian / Ubuntu / Mint: `update-ca-certificates`.
    UpdateCaCertificates,
    /// RHEL / Fedora / CentOS: `update-ca-trust`.
    UpdateCaTrust,
    /// Nothing found — log a warning.
    None,
}

/// Snapshot of the host trust environment, captured so detection is a pure
/// function testable without touching the real system.
#[cfg(target_os = "linux")]
#[derive(Debug)]
pub(crate) struct LinuxTrustEnv {
    pub(crate) ca_tool: LinuxCaTool,
    /// Absolute path to `certutil`, if available.
    pub(crate) certutil_path: Option<PathBuf>,
    /// All NSS database directories found in the user's home.
    pub(crate) nss_db_dirs: Vec<PathBuf>,
}

#[cfg(target_os = "linux")]
fn install_impl(ca_cert_path: &Path) -> Result<()> {
    let env = detect_trust_env();
    install_system_ca(ca_cert_path, &env)?;
    install_nss_dbs(ca_cert_path, &env);
    Ok(())
}

#[cfg(target_os = "linux")]
fn uninstall_impl() -> Result<()> {
    let env = detect_trust_env();
    uninstall_system_ca(&env)?;
    uninstall_nss_dbs(&env);
    Ok(())
}

#[cfg(target_os = "linux")]
fn install_system_ca(ca_cert_path: &Path, env: &LinuxTrustEnv) -> Result<()> {
    match env.ca_tool {
        LinuxCaTool::UpdateCaCertificates => {
            let dest = system_cert_dest_debian();
            std::fs::copy(ca_cert_path, &dest)
                .with_context(|| format!("copy CA cert to {}", dest.display()))?;
            run_command("update-ca-certificates", &[] as &[&str]).context("update-ca-certificates")?;
            tracing::info!("Linux: installed CA cert to {} via update-ca-certificates", dest.display());
        }
        LinuxCaTool::UpdateCaTrust => {
            let dest = system_cert_dest_rhel();
            std::fs::copy(ca_cert_path, &dest)
                .with_context(|| format!("copy CA cert to {}", dest.display()))?;
            run_command("update-ca-trust", &["extract"] as &[&str]).context("update-ca-trust extract")?;
            tracing::info!("Linux: installed CA cert to {} via update-ca-trust", dest.display());
        }
        LinuxCaTool::None => {
            tracing::warn!(
                "Linux: no system CA update tool found (tried update-ca-certificates, \
                 update-ca-trust). To trust *.portzero.local in system tools, copy {} \
                 to your distro's CA anchor directory and run the appropriate update command.",
                ca_cert_path.display()
            );
        }
    }
    Ok(())
}

#[cfg(target_os = "linux")]
fn uninstall_system_ca(env: &LinuxTrustEnv) -> Result<()> {
    match env.ca_tool {
        LinuxCaTool::UpdateCaCertificates => {
            let dest = system_cert_dest_debian();
            if dest.exists() {
                std::fs::remove_file(&dest)
                    .with_context(|| format!("remove {}", dest.display()))?;
                run_command("update-ca-certificates", &[] as &[&str]).context("update-ca-certificates")?;
                tracing::info!("Linux: removed CA cert {} via update-ca-certificates", dest.display());
            }
        }
        LinuxCaTool::UpdateCaTrust => {
            let dest = system_cert_dest_rhel();
            if dest.exists() {
                std::fs::remove_file(&dest)
                    .with_context(|| format!("remove {}", dest.display()))?;
                run_command("update-ca-trust", &["extract"] as &[&str]).context("update-ca-trust extract")?;
                tracing::info!("Linux: removed CA cert {} via update-ca-trust", dest.display());
            }
        }
        LinuxCaTool::None => {}
    }
    Ok(())
}

#[cfg(target_os = "linux")]
fn install_nss_dbs(ca_cert_path: &Path, env: &LinuxTrustEnv) {
    let Some(ref certutil) = env.certutil_path else {
        if !env.nss_db_dirs.is_empty() {
            tracing::warn!(
                "Linux: NSS databases found ({} location(s)) but certutil is not installed. \
                 Browsers may not trust *.portzero.local. \
                 Fix: sudo apt install libnss3-tools  (or dnf install nss-tools)",
                env.nss_db_dirs.len()
            );
        }
        return;
    };
    for db_dir in &env.nss_db_dirs {
        let args = certutil_add_args(db_dir, ca_cert_path);
        if let Err(e) = run_command(certutil.to_str().unwrap_or("certutil"), &args) {
            tracing::warn!("Linux: failed to add CA to NSS DB {}: {e:#}", db_dir.display());
        } else {
            tracing::info!("Linux: added CA to NSS DB {}", db_dir.display());
        }
    }
}

#[cfg(target_os = "linux")]
fn uninstall_nss_dbs(env: &LinuxTrustEnv) {
    let Some(ref certutil) = env.certutil_path else {
        return;
    };
    for db_dir in &env.nss_db_dirs {
        let args = certutil_delete_args(db_dir);
        if let Err(e) = run_command(certutil.to_str().unwrap_or("certutil"), &args) {
            tracing::warn!("Linux: failed to remove CA from NSS DB {}: {e:#}", db_dir.display());
        } else {
            tracing::info!("Linux: removed CA from NSS DB {}", db_dir.display());
        }
    }
}

// --- Pure builders — unit-tested, no side effects --------------------------

/// Destination path for the CA cert on Debian/Ubuntu.
#[cfg_attr(not(target_os = "linux"), allow(dead_code))]
pub(crate) fn system_cert_dest_debian() -> PathBuf {
    PathBuf::from("/usr/local/share/ca-certificates").join(SYSTEM_CERT_NAME)
}

/// Destination path for the CA cert on RHEL/Fedora.
#[cfg_attr(not(target_os = "linux"), allow(dead_code))]
pub(crate) fn system_cert_dest_rhel() -> PathBuf {
    PathBuf::from("/etc/pki/ca-trust/source/anchors").join(SYSTEM_CERT_NAME)
}

/// `certutil` arguments to add the CA to an NSS database directory.
/// The trust flags `"C,,"` mean: trusted for TLS server auth, not for email or
/// object signing.
#[cfg_attr(not(any(target_os = "linux", target_os = "macos")), allow(dead_code))]
pub(crate) fn certutil_add_args(db_dir: &Path, cert_path: &Path) -> Vec<String> {
    vec![
        "-A".to_string(),
        "-d".to_string(),
        format!("sql:{}", db_dir.display()),
        "-t".to_string(),
        "C,,".to_string(),
        "-n".to_string(),
        CERT_NICKNAME.to_string(),
        "-i".to_string(),
        cert_path.display().to_string(),
    ]
}

/// `certutil` arguments to delete the CA from an NSS database directory.
#[cfg_attr(not(any(target_os = "linux", target_os = "macos")), allow(dead_code))]
pub(crate) fn certutil_delete_args(db_dir: &Path) -> Vec<String> {
    vec![
        "-D".to_string(),
        "-d".to_string(),
        format!("sql:{}", db_dir.display()),
        "-n".to_string(),
        CERT_NICKNAME.to_string(),
    ]
}

/// Collect all NSS database directories found under `home`.
///
/// Checked locations:
/// - `~/.pki/nssdb`                                              (Chrome, Chromium)
/// - `~/.mozilla/firefox/*/`                                     (Firefox)
/// - `~/.var/app/org.mozilla.firefox/.mozilla/firefox/*/`        (Firefox Flatpak)
/// - `~/snap/firefox/current/.mozilla/firefox/*/`                (Firefox Snap)
///
/// A directory is included only if it contains a `cert9.db` file (the SQLite
/// NSS store). Legacy `cert8.db` (Berkeley DB) is intentionally ignored; all
/// modern installs use the SQL store.
#[cfg_attr(not(target_os = "linux"), allow(dead_code))]
pub(crate) fn find_nss_dbs(home: &Path) -> Vec<PathBuf> {
    let mut dbs = Vec::new();

    // Chrome / Chromium — direct NSS DB directory.
    let pki = home.join(".pki/nssdb");
    if pki.join("cert9.db").exists() {
        dbs.push(pki);
    }

    // Firefox-family profile directories — enumerate subdirs for cert9.db.
    let firefox_bases = [
        home.join(".mozilla/firefox"),
        home.join(".var/app/org.mozilla.firefox/.mozilla/firefox"),
        home.join("snap/firefox/current/.mozilla/firefox"),
    ];
    for base in &firefox_bases {
        dbs.extend(nss_dbs_under(base));
    }

    dbs
}

/// Return subdirectories of `dir` that contain a `cert9.db` file.
#[cfg_attr(not(target_os = "linux"), allow(dead_code))]
fn nss_dbs_under(dir: &Path) -> Vec<PathBuf> {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return vec![];
    };
    entries
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.is_dir() && p.join("cert9.db").exists())
        .collect()
}

// --- System detection — impure shims kept thin ----------------------------

#[cfg(target_os = "linux")]
fn detect_trust_env() -> LinuxTrustEnv {
    let home = effective_home_dir();
    LinuxTrustEnv {
        ca_tool: detect_ca_tool(),
        certutil_path: find_certutil(),
        nss_db_dirs: home.map(|h| find_nss_dbs(&h)).unwrap_or_default(),
    }
}

/// Resolve the real user's home directory.
///
/// When running under `sudo`, `$SUDO_USER` names the original caller.  We
/// look up their home from `/etc/passwd` so NSS database paths resolve
/// correctly even when root's `$HOME` is `/root`.
#[cfg(target_os = "linux")]
fn effective_home_dir() -> Option<PathBuf> {
    // Prefer the invoking user when running under sudo.
    if let Ok(sudo_user) = std::env::var("SUDO_USER") {
        if !sudo_user.is_empty() && sudo_user != "root" {
            if let Some(home) = passwd_home(&sudo_user) {
                return Some(home);
            }
        }
    }
    // Fall back to $HOME, then dirs::home_dir().
    std::env::var("HOME")
        .ok()
        .map(PathBuf::from)
        .or_else(dirs::home_dir)
}

/// Parse `/etc/passwd` to find the home directory for `username`.
#[cfg(target_os = "linux")]
fn passwd_home(username: &str) -> Option<PathBuf> {
    let content = std::fs::read_to_string("/etc/passwd").ok()?;
    for line in content.lines() {
        let mut fields = line.splitn(7, ':');
        let name = fields.next()?;
        if name != username {
            continue;
        }
        // Fields: name:pw:uid:gid:gecos:home:shell
        let home = fields.nth(4)?; // 0=pw,1=uid,2=gid,3=gecos,4=home
        return Some(PathBuf::from(home));
    }
    None
}

#[cfg(target_os = "linux")]
fn detect_ca_tool() -> LinuxCaTool {
    if command_exists("update-ca-certificates") {
        LinuxCaTool::UpdateCaCertificates
    } else if command_exists("update-ca-trust") {
        LinuxCaTool::UpdateCaTrust
    } else {
        LinuxCaTool::None
    }
}

#[cfg(target_os = "linux")]
fn find_certutil() -> Option<PathBuf> {
    // Absolute paths common on Debian/Ubuntu and RHEL.
    for candidate in &["/usr/bin/certutil", "/usr/local/bin/certutil"] {
        let p = Path::new(candidate);
        if p.exists() {
            return Some(p.to_path_buf());
        }
    }
    // Fall back to PATH lookup.
    let ok = matches!(
        std::process::Command::new("sh")
            .args(["-c", "command -v certutil >/dev/null 2>&1"])
            .status(),
        Ok(s) if s.success()
    );
    ok.then_some(PathBuf::from("certutil"))
}

#[cfg(any(target_os = "linux", target_os = "macos"))]
fn command_exists(cmd: &str) -> bool {
    matches!(
        std::process::Command::new("sh")
            .args(["-c", &format!("command -v {cmd} >/dev/null 2>&1")])
            .status(),
        Ok(s) if s.success()
    )
}

#[cfg(any(target_os = "linux", target_os = "macos"))]
fn run_command(program: &str, args: &[impl AsRef<std::ffi::OsStr>]) -> Result<()> {
    let status = std::process::Command::new(program)
        .args(args)
        .status()
        .with_context(|| format!("spawn {program}"))?;
    if !status.success() {
        anyhow::bail!("{program} exited with {status}");
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// macOS
// ---------------------------------------------------------------------------

/// Snapshot of the macOS trust environment, captured so detection is a pure
/// function testable without touching the real system.
#[cfg(target_os = "macos")]
#[derive(Debug)]
pub(crate) struct MacosTrustEnv {
    /// Absolute path to `certutil`, if available (`brew install nss`).
    pub(crate) certutil_path: Option<PathBuf>,
    /// All Firefox NSS database directories found in the user's home.
    pub(crate) nss_db_dirs: Vec<PathBuf>,
}

#[cfg(target_os = "macos")]
fn install_impl(ca_cert_path: &Path) -> Result<()> {
    install_system_keychain(ca_cert_path)?;
    let env = detect_macos_trust_env();
    install_nss_dbs_macos(ca_cert_path, &env);
    Ok(())
}

#[cfg(target_os = "macos")]
fn uninstall_impl() -> Result<()> {
    uninstall_system_keychain()?;
    let env = detect_macos_trust_env();
    uninstall_nss_dbs_macos(&env);
    Ok(())
}

#[cfg(target_os = "macos")]
fn install_system_keychain(ca_cert_path: &Path) -> Result<()> {
    let cert_str = ca_cert_path
        .to_str()
        .ok_or_else(|| anyhow::anyhow!("CA cert path is not valid UTF-8"))?;
    run_command(
        "security",
        &[
            "add-trusted-cert",
            "-d",
            "-r",
            "trustRoot",
            "-k",
            "/Library/Keychains/System.keychain",
            cert_str,
        ],
    )
    .context("security add-trusted-cert")?;
    tracing::info!("macOS: installed CA cert to system keychain");
    Ok(())
}

#[cfg(target_os = "macos")]
fn uninstall_system_keychain() -> Result<()> {
    // Gracefully ignore failures — the cert may not be present.
    match run_command(
        "security",
        &[
            "delete-certificate",
            "-c",
            CERT_NICKNAME,
            "-t",
            "/Library/Keychains/System.keychain",
        ],
    ) {
        Ok(()) => tracing::info!("macOS: removed CA cert from system keychain"),
        Err(e) => tracing::warn!(
            "macOS: could not remove CA from system keychain (may not be present): {e:#}"
        ),
    }
    Ok(())
}

#[cfg(target_os = "macos")]
fn install_nss_dbs_macos(ca_cert_path: &Path, env: &MacosTrustEnv) {
    let Some(ref certutil) = env.certutil_path else {
        if !env.nss_db_dirs.is_empty() {
            tracing::warn!(
                "macOS: Firefox NSS databases found ({} location(s)) but certutil is not \
                 installed. Firefox may not trust *.portzero.local. \
                 Fix: brew install nss",
                env.nss_db_dirs.len()
            );
        }
        return;
    };
    for db_dir in &env.nss_db_dirs {
        let args = certutil_add_args(db_dir, ca_cert_path);
        if let Err(e) = run_command(certutil.to_str().unwrap_or("certutil"), &args) {
            tracing::warn!("macOS: failed to add CA to NSS DB {}: {e:#}", db_dir.display());
        } else {
            tracing::info!("macOS: added CA to NSS DB {}", db_dir.display());
        }
    }
}

#[cfg(target_os = "macos")]
fn uninstall_nss_dbs_macos(env: &MacosTrustEnv) {
    let Some(ref certutil) = env.certutil_path else {
        return;
    };
    for db_dir in &env.nss_db_dirs {
        let args = certutil_delete_args(db_dir);
        if let Err(e) = run_command(certutil.to_str().unwrap_or("certutil"), &args) {
            tracing::warn!(
                "macOS: failed to remove CA from NSS DB {}: {e:#}",
                db_dir.display()
            );
        } else {
            tracing::info!("macOS: removed CA from NSS DB {}", db_dir.display());
        }
    }
}

/// Collect all Firefox NSS database directories found under a macOS home dir.
///
/// Checked locations:
/// - `~/Library/Application Support/Firefox/Profiles/*/`
/// - `~/Library/Application Support/Firefox Developer Edition/Profiles/*/`
/// - `~/Library/Application Support/Firefox Nightly/Profiles/*/`
///
/// Chrome and Chromium on macOS delegate to the system keychain, not NSS,
/// so only Firefox-family installs need `certutil` treatment.
/// A directory is included only if it contains a `cert9.db` file.
#[cfg_attr(not(target_os = "macos"), allow(dead_code))]
pub(crate) fn find_nss_dbs_macos(home: &Path) -> Vec<PathBuf> {
    let bases = [
        home.join("Library/Application Support/Firefox/Profiles"),
        home.join("Library/Application Support/Firefox Developer Edition/Profiles"),
        home.join("Library/Application Support/Firefox Nightly/Profiles"),
    ];
    let mut dbs = Vec::new();
    for base in &bases {
        dbs.extend(nss_dbs_under(base));
    }
    dbs
}

#[cfg(target_os = "macos")]
fn detect_macos_trust_env() -> MacosTrustEnv {
    MacosTrustEnv {
        certutil_path: find_certutil_macos(),
        nss_db_dirs: dirs::home_dir()
            .map(|h| find_nss_dbs_macos(&h))
            .unwrap_or_default(),
    }
}

/// Search for `certutil` in locations populated by `brew install nss`.
#[cfg(target_os = "macos")]
fn find_certutil_macos() -> Option<PathBuf> {
    for candidate in &[
        "/opt/homebrew/bin/certutil", // Homebrew Apple Silicon
        "/usr/local/bin/certutil",    // Homebrew Intel
    ] {
        let p = Path::new(candidate);
        if p.exists() {
            return Some(p.to_path_buf());
        }
    }
    // Last-resort PATH lookup.
    command_exists("certutil").then_some(PathBuf::from("certutil"))
}

// ---------------------------------------------------------------------------
// Windows — placeholder for the next PR
// ---------------------------------------------------------------------------

#[cfg(target_os = "windows")]
fn install_impl(_ca_cert_path: &Path) -> Result<()> {
    tracing::warn!("Windows trust store installation not yet implemented");
    Ok(())
}

#[cfg(target_os = "windows")]
fn uninstall_impl() -> Result<()> {
    Ok(())
}

// ---------------------------------------------------------------------------
// Unsupported platforms
// ---------------------------------------------------------------------------

#[cfg(not(any(target_os = "linux", target_os = "macos", target_os = "windows")))]
fn install_impl(_ca_cert_path: &Path) -> Result<()> {
    tracing::warn!("trust store installation not supported on this platform");
    Ok(())
}

#[cfg(not(any(target_os = "linux", target_os = "macos", target_os = "windows")))]
fn uninstall_impl() -> Result<()> {
    Ok(())
}

// ---------------------------------------------------------------------------
// Tests — purely functional; never write to the real system
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // --- System CA paths ---

    #[test]
    fn debian_cert_dest_is_correct() {
        let dest = system_cert_dest_debian();
        assert_eq!(
            dest,
            PathBuf::from("/usr/local/share/ca-certificates/portzero-local-ca.crt")
        );
    }

    #[test]
    fn rhel_cert_dest_is_correct() {
        let dest = system_cert_dest_rhel();
        assert_eq!(
            dest,
            PathBuf::from("/etc/pki/ca-trust/source/anchors/portzero-local-ca.crt")
        );
    }

    // --- certutil argument builders ---

    #[test]
    fn certutil_add_args_format() {
        let db = PathBuf::from("/home/user/.pki/nssdb");
        let cert = PathBuf::from("/tmp/ca.crt");
        let args = certutil_add_args(&db, &cert);
        assert_eq!(args[0], "-A");
        assert_eq!(args[1], "-d");
        assert_eq!(args[2], "sql:/home/user/.pki/nssdb");
        assert_eq!(args[3], "-t");
        assert_eq!(args[4], "C,,", "trust flags: TLS server auth only");
        assert_eq!(args[5], "-n");
        assert_eq!(args[6], CERT_NICKNAME);
        assert_eq!(args[7], "-i");
        assert_eq!(args[8], "/tmp/ca.crt");
    }

    #[test]
    fn certutil_delete_args_format() {
        let db = PathBuf::from("/home/user/.pki/nssdb");
        let args = certutil_delete_args(&db);
        assert_eq!(args[0], "-D");
        assert_eq!(args[1], "-d");
        assert_eq!(args[2], "sql:/home/user/.pki/nssdb");
        assert_eq!(args[3], "-n");
        assert_eq!(args[4], CERT_NICKNAME);
    }

    #[test]
    fn certutil_add_uses_sql_prefix() {
        let db = PathBuf::from("/home/user/.mozilla/firefox/abc123.default");
        let cert = PathBuf::from("/tmp/ca.crt");
        let args = certutil_add_args(&db, &cert);
        assert!(args[2].starts_with("sql:"), "NSS SQL store requires sql: prefix");
    }

    // --- NSS DB discovery ---

    #[test]
    fn find_nss_dbs_picks_up_pki_nssdb() {
        let dir = tempfile::tempdir().unwrap();
        let home = dir.path();
        let nssdb = home.join(".pki/nssdb");
        std::fs::create_dir_all(&nssdb).unwrap();
        std::fs::write(nssdb.join("cert9.db"), b"").unwrap();

        let found = find_nss_dbs(home);
        assert!(found.contains(&nssdb), "should find ~/.pki/nssdb");
    }

    #[test]
    fn find_nss_dbs_picks_up_firefox_profiles() {
        let dir = tempfile::tempdir().unwrap();
        let home = dir.path();
        let profile = home.join(".mozilla/firefox/abc123.default-release");
        std::fs::create_dir_all(&profile).unwrap();
        std::fs::write(profile.join("cert9.db"), b"").unwrap();

        let found = find_nss_dbs(home);
        assert!(found.contains(&profile), "should find Firefox profile NSS DB");
    }

    #[test]
    fn find_nss_dbs_ignores_dirs_without_cert9_db() {
        let dir = tempfile::tempdir().unwrap();
        let home = dir.path();
        // A Firefox profile dir without cert9.db — should be ignored.
        let profile = home.join(".mozilla/firefox/xyz.default");
        std::fs::create_dir_all(&profile).unwrap();

        assert!(find_nss_dbs(home).is_empty());
    }

    #[test]
    fn find_nss_dbs_empty_when_no_browsers_installed() {
        let dir = tempfile::tempdir().unwrap();
        assert!(find_nss_dbs(dir.path()).is_empty());
    }

    #[test]
    fn find_nss_dbs_ignores_legacy_cert8_db() {
        let dir = tempfile::tempdir().unwrap();
        let home = dir.path();
        let nssdb = home.join(".pki/nssdb");
        std::fs::create_dir_all(&nssdb).unwrap();
        // Only cert8.db present — we require cert9.db (SQL store).
        std::fs::write(nssdb.join("cert8.db"), b"").unwrap();

        assert!(find_nss_dbs(home).is_empty());
    }

    // --- passwd home parsing ---

    // --- macOS NSS DB discovery ---

    #[test]
    fn find_nss_dbs_macos_picks_up_firefox_profiles() {
        let dir = tempfile::tempdir().unwrap();
        let home = dir.path();
        let profile = home.join("Library/Application Support/Firefox/Profiles/abc123.default-release");
        std::fs::create_dir_all(&profile).unwrap();
        std::fs::write(profile.join("cert9.db"), b"").unwrap();

        let found = find_nss_dbs_macos(home);
        assert!(found.contains(&profile), "should find Firefox profile NSS DB");
    }

    #[test]
    fn find_nss_dbs_macos_picks_up_dev_edition() {
        let dir = tempfile::tempdir().unwrap();
        let home = dir.path();
        let profile =
            home.join("Library/Application Support/Firefox Developer Edition/Profiles/dev.default");
        std::fs::create_dir_all(&profile).unwrap();
        std::fs::write(profile.join("cert9.db"), b"").unwrap();

        let found = find_nss_dbs_macos(home);
        assert!(found.contains(&profile), "should find Firefox Dev Edition NSS DB");
    }

    #[test]
    fn find_nss_dbs_macos_picks_up_nightly() {
        let dir = tempfile::tempdir().unwrap();
        let home = dir.path();
        let profile =
            home.join("Library/Application Support/Firefox Nightly/Profiles/nightly.default");
        std::fs::create_dir_all(&profile).unwrap();
        std::fs::write(profile.join("cert9.db"), b"").unwrap();

        let found = find_nss_dbs_macos(home);
        assert!(found.contains(&profile), "should find Firefox Nightly NSS DB");
    }

    #[test]
    fn find_nss_dbs_macos_empty_when_no_firefox() {
        let dir = tempfile::tempdir().unwrap();
        assert!(find_nss_dbs_macos(dir.path()).is_empty());
    }

    #[test]
    fn find_nss_dbs_macos_ignores_profile_without_cert9_db() {
        let dir = tempfile::tempdir().unwrap();
        let home = dir.path();
        let profile = home.join("Library/Application Support/Firefox/Profiles/no-cert.default");
        std::fs::create_dir_all(&profile).unwrap();
        // No cert9.db written.

        assert!(find_nss_dbs_macos(home).is_empty());
    }

    #[cfg(target_os = "linux")]
    #[test]
    fn passwd_home_finds_user() {
        let dir = tempfile::tempdir().unwrap();
        let passwd = dir.path().join("passwd");
        std::fs::write(
            &passwd,
            "root:x:0:0:root:/root:/bin/bash\nalice:x:1000:1000:Alice:/home/alice:/bin/bash\n",
        )
        .unwrap();
        let content = std::fs::read_to_string(&passwd).unwrap();
        // Inline the parsing logic against our test file.
        let home: Option<PathBuf> = content.lines().find_map(|line| {
            let mut fields = line.splitn(7, ':');
            let name = fields.next()?;
            if name != "alice" {
                return None;
            }
            let home = fields.nth(4)?;
            Some(PathBuf::from(home))
        });
        assert_eq!(home, Some(PathBuf::from("/home/alice")));
    }
}
