//! OS trust store installation for the PortZero local CA.
//!
//! Installs the self-signed CA generated by [`super::ca`] into the platform
//! trust stores so browsers and `curl` accept `*.portzero.local` HTTPS certs
//! without warnings. Each platform provisions two independent stores (a
//! system-wide store plus per-browser NSS databases); see the [`linux`],
//! [`macos`], and [`windows`] submodules for the specifics. Uninstall reverses
//! both steps, and both operations are idempotent.
//!
//! The cross-platform helpers and the pure path/argument builders live in
//! [`common`], which is compiled on every platform so they can be unit-tested
//! without touching the real system.

use std::path::Path;

use anyhow::Result;

mod common;

#[cfg(target_os = "linux")]
mod linux;
#[cfg(target_os = "macos")]
mod macos;
#[cfg(target_os = "windows")]
mod windows;

#[cfg(target_os = "linux")]
use linux::{install_impl, uninstall_impl, verify_installation_impl};
#[cfg(target_os = "macos")]
use macos::{install_impl, uninstall_impl, verify_installation_impl};
#[cfg(target_os = "windows")]
use windows::{install_impl, uninstall_impl, verify_installation_impl};

#[cfg(any(target_os = "linux", target_os = "macos", target_os = "windows"))]
pub(crate) use common::run_command_capture_with_timeout;

/// Install the PortZero local CA into OS trust stores.
///
/// `ca_cert_path` is the on-disk path of the PEM file (as returned by
/// [`super::ca::LocalCa::ca_cert_path`]). The file must already exist.
pub fn install(ca_cert_path: &Path) -> Result<()> {
    install_impl(ca_cert_path)
}

/// Remove the PortZero local CA from OS trust stores.
pub fn uninstall() -> Result<()> {
    uninstall_impl()
}

/// Summary of trust-store verification results.
#[derive(Debug, Clone, Default)]
pub struct TrustVerificationReport {
    /// Human-readable descriptions of stores that are missing the PortZero CA.
    pub missing: Vec<String>,
}

impl TrustVerificationReport {
    /// Return `true` when every verified store contains the CA.
    pub fn is_clean(&self) -> bool {
        self.missing.is_empty()
    }
}

/// Verify that the local CA is still installed in the trust stores PortZero
/// manages on this platform.
pub fn verify_installation(ca_cert_path: &Path) -> Result<TrustVerificationReport> {
    verify_installation_impl(ca_cert_path)
}

#[cfg(not(any(target_os = "linux", target_os = "macos", target_os = "windows")))]
fn install_impl(_ca_cert_path: &Path) -> Result<()> {
    tracing::warn!("trust store installation not supported on this platform");
    Ok(())
}

#[cfg(not(any(target_os = "linux", target_os = "macos", target_os = "windows")))]
fn uninstall_impl() -> Result<()> {
    Ok(())
}

#[cfg(not(any(target_os = "linux", target_os = "macos", target_os = "windows")))]
fn verify_installation_impl(_ca_cert_path: &Path) -> Result<TrustVerificationReport> {
    Ok(TrustVerificationReport::default())
}

#[cfg(test)]
mod tests;
